hexagonal-dependency:
  active: true

  DomainCannotDependOnAdapters:
    active: true
    domainPackages: ['domain', 'core']
    adapterPackages: ['adapter', 'adapters', 'infrastructure']

  DomainCannotDependOnApi:
    active: true
    domainPackages: ['domain', 'core']
    apiPackages: ['api', 'controller', 'controllers', 'rest']

  ApiCannotDependOnAdapters:
    active: true
    apiPackages: ['api', 'controller', 'controllers', 'rest']
    adapterPackages: ['adapter', 'adapters', 'infrastructure']

  ApiCannotDependOnPorts:
    active: true
    apiPackages: ['api', 'controller', 'controllers', 'rest']
    portSuffixes: ['Port', 'Repository', 'Gateway', 'Client']
    allowedPortTypes: []
